# Generated by Django 4.1.2 on 2022-10-24 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('foodlist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteFoodPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('foodlist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.DateTimeField(null=True)),
                ('index', models.IntegerField(null=True)),
                ('has_died', models.BooleanField(default=False)),
                ('balance', models.CharField(max_length=100)),
                ('eyeColor', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('about', models.TextField(null=True)),
                ('greeting', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pandora.company')),
                ('favoriteFood', models.ManyToManyField(to='pandora.favoritefoodpeople')),
                ('friends', models.ManyToManyField(to='pandora.friend')),
            ],
        ),
    ]
